### ISSUE TITLE
update configuration file to specify input file names

### ISSUE THREAD

**Issue by anardek** [UNC-CECL/Barrier3D#7]
@mcflugen, as we discussed awhile back, the configuration file and load_inputs is unnecessarily complicated (we don't need numpy and csv, but I think we can keep this extra code just in case). We also can't easily specify input files with multiple prefixes. I suggest that we add the file names (e.g., "barrier3d-elevations.csv") as an input item in the yaml. That way we can use an elevation, storm, and growth parameter file all with different prefixes (i.e., not all "barrier3d"). Thoughts? I started to look into what I would need to update the configuration file; do you know if exconfig has a "StringField" option?

**Comment by anardek** [comment]
Other things: 

- [ ] The flow routing algorithm is slow (see other issue, @mcflugen is on it)
- [ ] The shrubs code needs to be updated and tested (@irbreeves is on it)
- [ ] Modifying the storm time series for each simulation is overly complicated and not user friendly (@anardek my current task)
- [ ] We need to add that bit of code for formatting for the black style (@mcflugen)

**Comment by anardek** [comment]
@mcflugen, we had some merge conflicts that I had to manually address. Some checks aren't passing now. Not sure what I screwed up.

**Comment by mcflugen** [comment]
@anardek There look to be two issues:
* The *load_inputs* function used to calculate a variable, *SH* (shrub height, I think), but it no longer does. As such, tests that used to look for the existence of this parameter are now failing.
* Probably just a typo in *barrier3d.py*: *bermEl* instead of *BermEl*.

I'll get a pull request together right now to fix these two issues.
